<?php
declare(strict_types=1);

// Nekosbest SDK utility registration

require_once __DIR__ . '/../core/UtilityType.php';
require_once __DIR__ . '/Clean.php';
require_once __DIR__ . '/Done.php';
require_once __DIR__ . '/MakeError.php';
require_once __DIR__ . '/FeatureAdd.php';
require_once __DIR__ . '/FeatureHook.php';
require_once __DIR__ . '/FeatureInit.php';
require_once __DIR__ . '/Fetcher.php';
require_once __DIR__ . '/MakeFetchDef.php';
require_once __DIR__ . '/MakeContext.php';
require_once __DIR__ . '/MakeOptions.php';
require_once __DIR__ . '/MakeRequest.php';
require_once __DIR__ . '/MakeResponse.php';
require_once __DIR__ . '/MakeResult.php';
require_once __DIR__ . '/MakePoint.php';
require_once __DIR__ . '/MakeSpec.php';
require_once __DIR__ . '/MakeUrl.php';
require_once __DIR__ . '/Param.php';
require_once __DIR__ . '/PrepareAuth.php';
require_once __DIR__ . '/PrepareBody.php';
require_once __DIR__ . '/Graphql.php';
require_once __DIR__ . '/PrepareHeaders.php';
require_once __DIR__ . '/PrepareMethod.php';
require_once __DIR__ . '/PrepareParams.php';
require_once __DIR__ . '/PreparePath.php';
require_once __DIR__ . '/PrepareQuery.php';
require_once __DIR__ . '/ResultBasic.php';
require_once __DIR__ . '/ResultBody.php';
require_once __DIR__ . '/ResultHeaders.php';
require_once __DIR__ . '/TransformRequest.php';
require_once __DIR__ . '/TransformResponse.php';

NekosbestUtility::setRegistrar(function (NekosbestUtility $u): void {
    $u->clean = [NekosbestClean::class, 'call'];
    $u->done = [NekosbestDone::class, 'call'];
    $u->make_error = [NekosbestMakeError::class, 'call'];
    $u->feature_add = [NekosbestFeatureAdd::class, 'call'];
    $u->feature_hook = [NekosbestFeatureHook::class, 'call'];
    $u->feature_init = [NekosbestFeatureInit::class, 'call'];
    $u->fetcher = [NekosbestFetcher::class, 'call'];
    $u->make_fetch_def = [NekosbestMakeFetchDef::class, 'call'];
    $u->make_context = [NekosbestMakeContext::class, 'call'];
    $u->make_options = [NekosbestMakeOptions::class, 'call'];
    $u->make_request = [NekosbestMakeRequest::class, 'call'];
    $u->make_response = [NekosbestMakeResponse::class, 'call'];
    $u->make_result = [NekosbestMakeResult::class, 'call'];
    $u->make_point = [NekosbestMakePoint::class, 'call'];
    $u->make_spec = [NekosbestMakeSpec::class, 'call'];
    $u->make_url = [NekosbestMakeUrl::class, 'call'];
    $u->param = [NekosbestParam::class, 'call'];
    $u->prepare_auth = [NekosbestPrepareAuth::class, 'call'];
    $u->prepare_body = [NekosbestPrepareBody::class, 'call'];
    $u->prepare_headers = [NekosbestPrepareHeaders::class, 'call'];
    $u->prepare_method = [NekosbestPrepareMethod::class, 'call'];
    $u->prepare_params = [NekosbestPrepareParams::class, 'call'];
    $u->prepare_path = [NekosbestPreparePath::class, 'call'];
    $u->prepare_query = [NekosbestPrepareQuery::class, 'call'];
    $u->graphql_body = [NekosbestGraphql::class, 'body'];
    $u->graphql_errors = [NekosbestGraphql::class, 'errors'];
    $u->result_basic = [NekosbestResultBasic::class, 'call'];
    $u->result_body = [NekosbestResultBody::class, 'call'];
    $u->result_headers = [NekosbestResultHeaders::class, 'call'];
    $u->transform_request = [NekosbestTransformRequest::class, 'call'];
    $u->transform_response = [NekosbestTransformResponse::class, 'call'];
});
